export default [{
  url: 'settings',
  icon: 'settings',
  text: 'Settings',
  className: 'settings'
}, {
  url: 'chrome://flags',
  icon: 'flag',
  text: 'Flags',
  className: 'chrome-flags'
}, {
  url: 'chrome://inspect',
  icon: 'inspect',
  text: 'Inspect',
  className: 'chrome-inspect'
}, {
  url: 'chrome://history',
  icon: 'history',
  text: 'History',
  className: 'chrome-history'
}, {
  url: 'chrome://bookmarks',
  icon: 'bookmark',
  text: 'Bookmarks',
  className: 'chrome-bookmarks'
}, {
  url: 'chrome://downloads',
  icon: 'download',
  text: 'Downloads',
  className: 'chrome-downloads'
}, {
  url: 'chrome://extensions',
  icon: 'extensions',
  text: 'Extensions',
  className: 'chrome-extensions'
}, {
  url: 'chrome://apps',
  icon: 'apps',
  text: 'Applications',
  className: 'chrome-apps'
}, {
  url: 'https://chrome.google.com/webstore',
  icon: 'store',
  text: 'ChromeWebStore',
  className: 'chrome-store'
}];
